### ISSUE TITLE
Add Unit Test For - Binary Tree preOrder Traversal

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#105]
### 👽 What is required?
Function to test: `preOrder();`
The algorithm is here : [Binary Tree](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/BinaryTree)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by reshmisaji** [comment]
can I pick this up?

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#111 ]
