### ISSUE TITLE
Add Unit Test For - Trie search string

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#106]
### 👽 What is required?
Function to test: `search();`
The algorithm is here : [Trie](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/Trie)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by reshmisaji** [comment]
can i pick this up?

**Comment by eyeamkd** [comment]
Hey @reshmisaji if you aren't working on this, can I pick this up?

**Comment by ashokdey** [comment]
Sure, go ahead @eyeamkd
