### ISSUE TITLE
Hey! we can have CD as well.

### ISSUE THREAD

**Issue by sanyamdogra** [knaxus/problem-solving-javascript#108]
🤖  Why I am worried?

I can see that the CI here is working great and I have an idea of having CD as well.

To have a **CD pipeline** in place we can do the following:
- Create a web page of problem listing 
- Create an express server to serve that weeb page
- Finally, Heroku can be used to showcase the repo to the world in the form of a website

🎉

**Comment by ashokdey** [comment]
Hey @sanyamdogra this is indeed a good idea and I have assigned @TheJSGirl to work on it. Thanks

👏
