### ISSUE TITLE
Added get all path of a M x N grid.

### ISSUE THREAD

**Issue by navneet15** [knaxus/problem-solving-javascript#11]
Hey! I have just added a new problem.
Can you please review it so that I can make a PR.

**Comment by ashokdey** [comment]
Hello @navneet15, I was going very busy since the last couple of days. Your code has been reviewed by @TheSTL a long ago.

Also, next time when you open an issue, please add the PR number and branch name for ease of navigation. 

Thanks for your contributions 🥇 😊
