### ISSUE TITLE
Traverse Binary Tree In ZigZag Order

### ISSUE THREAD

**Issue by ashu8912** [knaxus/problem-solving-javascript#112]
![Screenshot 2019-10-19 at 6 02 31 PM](https://user-images.githubusercontent.com/30126128/67144981-b958ca00-f29a-11e9-9397-4de576c81284.png)
Add This Question To Binary Tree Section.

**Comment by ashu8912** [comment]
I can work on this if you want.

**Comment by ashokdey** [comment]
Assigning you @ashu8912

**Comment by kajal1811** [comment]
Is this issue still open? If yes, I would like to work on it.
