### ISSUE TITLE
All Permutations of a String Problem

### ISSUE THREAD

**Issue by ashu8912** [knaxus/problem-solving-javascript#116]
![Screenshot 2019-10-20 at 9 02 14 AM](https://user-images.githubusercontent.com/30126128/67154356-5b6ac780-f318-11e9-92d3-de659306646d.png)
![Screenshot 2019-10-20 at 9 02 09 AM](https://user-images.githubusercontent.com/30126128/67154357-6160a880-f318-11e9-9d5d-7d9331b32161.png)

This is a famous backtracking problem

**Comment by ashu8912** [comment]
I can work on this one

**Comment by TheSTL** [comment]
I'm closing this issue because  problem is already present in repo : [get-string-permutations](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Problems_/get-string-permutations)
