### ISSUE TITLE
 Bottom View of a Binary Tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#120]
Create a new folder `bottom-view-binary-tree` in [Binary Tree](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/BinaryTree) .
Use implemented [BinaryTree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/BinaryTree/index.js).
Problem is statement here: [bottom-view-binary-tree](https://www.geeksforgeeks.org/bottom-view-binary-tree/).

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by karimelazzouni** [comment]
Will work on this.

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is [#130 ]
