### ISSUE TITLE
print-nodes-top-view-binary-tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#121]
Create a new folder `print-nodes-top-view-binary-tree` in [Binary Tree](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/BinaryTree) .
Use implemented [BinaryTree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/BinaryTree/index.js).
Problem is statement here: [print-nodes-top-view-binary-tree](https://www.geeksforgeeks.org/print-nodes-top-view-binary-tree/).

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by ngittlen** [comment]
I can do this one.

**Comment by TheSTL** [comment]
You can do this @ngittlen :+1:

**Comment by kajal1811** [comment]
If this issue is not resolved, can you assign me so that I can contribute to it?
