### ISSUE TITLE
Check if a binary tree is subtree of another binary tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#122]
Create a new folder `check-binary-tree-subtree-another-binary-tree` in [Binary Tree](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/BinaryTree) .
Use implemented [BinaryTree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/BinaryTree/index.js).
Problem is statement here: [check-binary-tree-subtree-another-binary-tree](https://www.geeksforgeeks.org/check-binary-tree-subtree-another-binary-tree-set-2/).

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by apsychogirl** [comment]
Hi, Can I take this up?

**Comment by TheSTL** [comment]
Yes you can work on this @apsychogirl .

**Comment by abuasifkhan** [comment]
I didn't know we need to comment here. But I already made a pull request on this issue. :)

**Comment by ashima20** [comment]
hi is this resolved ?
I can work on this.

**Comment by ashokdey** [comment]
@ashima20 I have to check with @TheSTL, regardless you can start with it for the *Problems* section of the repo. Also, feel free to add your own problems. 
@apsychogirl you can take up other existing issues, we are also looking for code reviewers and maintainers.
@abuasifkhan can you refer your PR here in comments?
