### ISSUE TITLE
Knuth–Morris–Pratt(KMP) Pattern Matching(Substring search)

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#124]
### Knuth–Morris–Pratt(KMP) Pattern Matching(Substring search)
Problem: Given two string A and B. Check if A is Substring of B.
Return true if substring , else return false.
Create a new folder `KMP` in [Classics](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Classics_)
Highly recommended to watch this video to understand [KMP](https://www.youtube.com/watch?v=GTJr8OvyEVQ) 

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by jonathanmcchesney** [comment]
Can I take this one?

**Comment by TheSTL** [comment]
yes you can take this one @jonathanmcchesney

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is [#125 ]
