### ISSUE TITLE
Add Unit Test For Find unique-word-count in Trie

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#135]
### 👽 What is required?
Add unit test to find unique word count in a trie.
The algorithm is here : [unique-word-count](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/Trie/unique-word-count)

Contribution guide is here : [CONTRIBUTION](https://github.com/knaxus/problem-solving-javascript/blob/master/CONTRIBUTING.md)

Thank You!

**Comment by qualitymanifest** [comment]
I'd like to give this a shot. I'm not new to contributing to open source, but I am new to testing. I'll submit a PR in a bit.

**Comment by TheSTL** [comment]
Hi @qualitymanifest .
Please try to achieve or  close to 100 percent code coverage.

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#138 ]
