### ISSUE TITLE
Add Unit Test for to find total word count in Trie

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#136]
### 👽 What is required?
Add unit test to find total word count in a trie.
The algorithm is here : [total-words-in-trie](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/Trees/Trie/total-words-in-trie)

Contribution guide is here : [CONTRIBUTION](https://github.com/knaxus/problem-solving-javascript/blob/master/CONTRIBUTING.md)

Thank You!

**Comment by niyonx** [comment]
Hi, can I work on this issue?

**Comment by TheSTL** [comment]
Yes you can work on this @niyonx .
