### ISSUE TITLE
Add Unit Test For - get-unique-words for Trie

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#143]
### 👽 What is required?
The algorithm is here : [get-unique-words](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/Trie/get-unique-words/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by garrowp** [comment]
I can pick up this one

**Comment by ashokdey** [comment]
Thanks for taking interest @garrowp, however, we already have #148 and #149. Can you continue with the changes asked in those two PRs?

**Comment by garrowp** [comment]
Sure!

**Comment by ashokdey** [comment]
You can pick up those
