### ISSUE TITLE
Add Unit Test for - all-words-in-trie in Trie

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#144]
### 👽 What is required?
The algorithm is here : [all-words-in-trie](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/Trie/all-words-in-trie/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by garrowp** [comment]
I can take this one
