### ISSUE TITLE
Add Unit Test for - check-binary-tree-subtree-another-binary-tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#145]
### 👽 What is required?
The algorithm is here : [check-binary-tree-subtree-another-binary-tree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/BinaryTree/check-binary-tree-subtree-another-binary-tree/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by jyburns** [comment]
Hi, @TheSTL 

I would like to work on this issue 👍

**Comment by caseycling** [comment]
Can I work on this issue?

**Comment by ashokdey** [comment]
sure

**Comment by caseycling** [comment]
Can you help point me in the right direction of how to add the tests? Maybe another file which has other tests already written? Apologies, still very much a noob when it comes to unit testing.

**Comment by ashokdey** [comment]
@caseycling you can have a tour of the repository and you will get to know the format of both code and test files.

**Comment by shraddha-shetty** [comment]
can i work on  this issue
