### ISSUE TITLE
Add Unit Test for - bottom-view-binary-tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#146]
### 👽 What is required?
The algorithm is here : [bottom-view-binary-tree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/BinaryTree/bottom-view-binary-tree/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by christian-fei** [comment]
i'm on it 👌

**Comment by christian-fei** [comment]
here we go https://github.com/knaxus/problem-solving-javascript/pull/147

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#147 ]
