### ISSUE TITLE
Add unit tests for solved problems

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#16]
Hello folks! Unit testing is one of the best ways to build robust applications. If you are a beginner, it's a great place to start with **Unit Testing** and your **Open Source** contribution journey.

You can find ample of examples in the repo itself and hence can kickstart with the unit tests for solutions not having test cases.

**Comment by LeoSL** [comment]
I'd like to work on this one.

**Question:**
- Should I add tests for **all** the problems that don't have tests today?

**Comment by marcelinol** [comment]
I'll add some more as well

**Comment by ashokdey** [comment]
> I'd like to work on this one.
> 
> **Question:**
> 
> * Should I add tests for **all** the problems that don't have tests today?

Yes please go ahead @LeoSL this would be really helpful. I am assigning this issue to you. Let me know if you would like to take up the responsibility of the Test Cases for this repo. 

Thanks! 😊 ❤️

**Comment by ashokdey** [comment]
> I'll add some more as well

Hello @marcelinol, thanks for your contributions too! Let me know if anything else you would like to do for this repo or any of the repo of this organization **[Knaxus](https://github.com/knaxus)**

**Comment by LeoSL** [comment]
@ashokdey I'd be glad to take it up, do you have some doc that outlines the main responsibilities? Can you provide more details?

**Comment by ashokdey** [comment]
I am working on the documentation part and I will post it by tomorrow.

**Comment by ashokdey** [comment]
Hello @LeoSL, as said, you can find the guidelines here: [Contribution Guide](https://github.com/knaxus/problem-solving-javascript/blob/master/README.md#contribution-guide)

**Comment by ashokdey** [comment]
Closing due to no response
