### ISSUE TITLE
Balanced Paratheses Problem

### ISSUE THREAD

**Issue by adarshaacharya** [knaxus/problem-solving-javascript#166]
**Check for balanced parentheses in the given string.**

```javascript
 ()() --> return true
 (((  --> return false
 ((()  --> return false

```

I want to implement this problem using reduce() method in JS.

![image](https://user-images.githubusercontent.com/50266088/86530187-549bd900-bed6-11ea-868f-efad4828d434.png)

Can I work on this problem ?

**Comment by ashokdey** [comment]
@adarshaacharya, have you raised the PR for the same?

**Comment by adarshaacharya** [comment]
@ashokdey  yeah !! I've raised PR for same problem.

**Comment by TanyaKhandelwal** [comment]
Hey! Is this issue still open?
I would like to contribute to this issue

**Comment by ashokdey** [comment]
@TanyaKhandelwal thanks for #187
