### ISSUE TITLE
Edit in Readme.md file of the project

### ISSUE THREAD

**Issue by JayeshJanyani** [knaxus/problem-solving-javascript#168]
Just correct the spelling of *Find* under contribution in Readme.md file of the repository. Can I do it?

PS- I am newbie, sorry for this silly issue.
If this is a valid issue, please assign it to me.

**Comment by ashokdey** [comment]
Every contribution counts. 

For more reach out to me on Twitter: 
- twitter.com/ashokdey_
- twitter.com/knaxus_

Thanks

**Comment by roshnaeem** [comment]
Can I work on this issue, I found a grammatical mistake too. I would like to fix both.

**Comment by roshnaeem** [comment]
@ashokdey Kindly review my PR https://github.com/knaxus/problem-solving-javascript/pull/174
