### ISSUE TITLE
Add new problems with solution

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#17]
If you are very new to the world of software development and you are finding it hard to start your open source contribution, here is the easiest way to kick-off! 

**This issue is not bounded to a single person**
**Mention the Problems you will be adding so that people do not collide**

- Add a logical problem with the solution
- Follow the pattern for file names and folder name (adding Contribution Guide ASAP)
- Add Unit Test as well to verify the solution

**Comment by SumeetHaryani** [comment]
Hi @ashokdey I would like to work on this issue.

**Comment by ashokdey** [comment]
> Hi @ashokdey I would like to work on this issue.

Assigning you, please mention the problems you will be solving so that people do not collide
