### ISSUE TITLE
maxArraySum Problem

### ISSUE THREAD

**Issue by shubhdwiv12** [knaxus/problem-solving-javascript#171]
Hi, I am new into open source project, I can see that we don't have maxArraySum() problem in the project. i would like to add this problem.

Problem Statement is as follows:-
1.  Write a function which takes an array and a number, now, it will find the maximum sum of consecutive subarray with the length of number passed to it, 

For example:-

maxArray([1,2,3,4], 2) //7 as [3+4]
maxArray([3,4], 4) // null as the length of subarray should be 4 

Request you to assign me this issue. I will work on it.

**Comment by Halasalhab** [comment]
So is this is done? or can I claim it?
