### ISSUE TITLE
minor copy update to LinkedList unit test

### ISSUE THREAD

**Issue by oukano** [knaxus/problem-solving-javascript#197]
in line 21, the it() should say `Should set the head, tail and size of a LinkedList` instead of 
`Should set the data and next field of a node`

https://github.com/knaxus/problem-solving-javascript/blob/ff5e81cbf2cc88ee1a83993c5f18789fe6e1419f/src/_DataStructures_/LinkedList/LinkedList.test.js#L21

i can take this if agreed

**Comment by sdkdeepa** [comment]
Hello ! I would like to make changes to this and raise a PR..

**Comment by ashokdey** [comment]
Go ahead @sdkdeepa

**Comment by sdkdeepa** [comment]
Please approve changes made to https://github.com/knaxus/problem-solving-javascript/pull/199
