### ISSUE TITLE
Add Unit Test for - postfix expression evaluation

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#34]
Add the Unit Test for #33 

What is required?

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the **Contribution Guide** is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by vobango** [comment]
Hello, @ashokdey I would like to work on this issue.

**Comment by ashokdey** [comment]
Sure @vobango go ahead, also if you like the work please share and add a star to the repo. Thanks
