### ISSUE TITLE
Add Unit Test for - A* algorithm

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#38]
## 🤖 What is required?

The algorithm is here : [A* pathFinder](https://github.com/knaxus/problem-solving-javascript/blob/master/src/PathFinder/AStart/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by ngittlen** [comment]
I'd like to work on this.

**Comment by TheSTL** [comment]
@ngittlen you can work on this.

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is [#100 ]
