### ISSUE TITLE
Add Unit Test for - Fibonacci

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#39]
### 👽 What is required?

The algorithm is here : [Fibonacci](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Classics_/fibonacci)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by PoojaKhandhadia** [comment]
I will work on it.

**Comment by ashokdey** [comment]
Hello @PoojaKhandhadia assigned you this issue

**Comment by ashu8912** [comment]
Hey @PoojaKhandhadia are you working on this one if not can i take this one.

**Comment by TheSTL** [comment]
I'm assigning this issue to you @ashu8912 .

**Comment by ashokdey** [comment]
@TheSTL is it done now?

**Comment by TheSTL** [comment]
@ashokdey it's not done now.

**Comment by ashokdey** [comment]
Ok.
