### ISSUE TITLE
Add Unit Test for - Caeser Cipher

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#40]
### 🤡 What is required?
The algorithm is here : [Caeser Cipher](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Classics_/caeser_cipher)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by fcosueza** [comment]
I can work on this. :+1:

**Comment by ashokdey** [comment]
Sure @fcosueza, I have assigned this issue to you.

**Comment by fcosueza** [comment]
Thanks !! :smiley:

**Comment by fcosueza** [comment]
Caesar cipher should raise and error when second argument is not a number, instead it return a string of "undefinedundefinedundefined". Also, the folder is misspeled "caeser". Should i correct it or make a new issue ?

**Comment by TheSTL** [comment]
@fcosueza 
You should make a new issue for this and correct it in a new PR.

**Comment by Omkaragrawal** [comment]
Hey,
 I would like to take this task.

**Comment by ashokdey** [comment]
> Hey,
> I would like to take this task.

Hey, @Omkaragrawal I have assigned you the fix and you can continue from there.
