### ISSUE TITLE
Add Unit Test for - Loop in list

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#41]
### 🤡 What is required?
The algorithm is here : [Loop in list](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_DataStructures_/LinkedList/loop-in-list)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by DaniloBarros** [comment]
I'll do it

**Comment by DaniloBarros** [comment]
PR made #46

**Comment by ashokdey** [comment]
PR #46 closes this issue. Thanks
