### ISSUE TITLE
Handling fibonacci for negative numbers and 0

### ISSUE THREAD

**Issue by PoojaKhandhadia** [knaxus/problem-solving-javascript#42]
Function **fibonacciTabular** is not handled if a negative number is provided. It returns undefined as output.

If 0 is given as index in **fibonacciTabular** it returns 0 instead of 1.

@ashokdey For the functions **fibonacci** and **fibonacciMemoized** if negative numbers are provided the output is coming as 1. Is it correct to handle in such a way that the output should be 1 or it should be handled that the output comes as 0?

**Comment by SumeetHaryani** [comment]
@ashokdey I would like to work on this issue.

**Comment by ashokdey** [comment]
Thanks @PoojaKhandhadia, I really appreciate your skills and efforts. I would also like to know whether you are interested to be a full-time maintainer of this project putting more stress on Unit Tests? 

Also thank you @SumeetHaryani, your PR #21 has fixed this. I am looping in @TheSTL for cross-validation before I close this.

**Comment by TheSTL** [comment]
It should throw error if index is negative.
And Fibonacci series start from 0,1,1,2,3........

**Comment by PoojaKhandhadia** [comment]
@ashokdey Sounds great!! Thanks for this. I would love to take this up!!!

**Comment by ashokdey** [comment]
Great @PoojaKhandhadia, please drop me a mail with your contact details and availability for this task here: [ad@ashokdey.in]() 🍾

**Comment by PoojaKhandhadia** [comment]
@ashokdey @TheSTL I was just going through this.... the current change returns the negative number itself instead of error.

**Comment by SumeetHaryani** [comment]
@PoojaKhandhadia working on it, will raise PR soon.
