### ISSUE TITLE
Caesar cipher 

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#44]
### ⚠️ Issue
Caesar cipher should raise and error when second argument is not a number, instead it's returning a string of "undefinedundefinedundefined"

**Comment by ashokdey** [comment]
Thanks, @fcosueza, for pointing out this in #40. I am taking up this.

**Comment by fcosueza** [comment]
You're welcome :smiley:

**Comment by Omkaragrawal** [comment]
Hey,
I would like to take up the task for Caesar Cipher, including testing, etc.

**Comment by ashokdey** [comment]
Okay, go ahead @Omkaragrawal 👍
