### ISSUE TITLE
Add Unit Test for - Get Smallest Common Number

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#47]
### 👽 What is required?
The algorithm is here : [get-smallest-common-number](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Problems_/get-smallest-common-number)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by dwncy** [comment]
Hi, I would like to take this :)

**Comment by TheSTL** [comment]
I'am closing this issue.
PR for this issue - [#50 ](https://github.com/knaxus/problem-solving-javascript/pull/50)
