### ISSUE TITLE
Add Unit Test for - Get Maze Path

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#48]
### 👽 What is required?
The algorithm is here : [get-mazePath](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_Problems_/get-mazePath/index.js)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by glennforrest** [comment]
Will give this a go

**Comment by TheSTL** [comment]
You can give it a shot @glennforrest

**Comment by TheSTL** [comment]
I'am closing this issue.
PR for this issue - [#53 ](https://github.com/knaxus/problem-solving-javascript/pull/53)
