### ISSUE TITLE
Display function should return an array

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#51]
[Display in Doubly Linked List](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/DoublyLinkedList/index.js) should not log to console, instead return an array so that I can be tested easily.

I am adding the same in Contribution guide and correcting for previous non-linear data structures

If you liked the work add a star to it.

**Comment by Mk996** [comment]
Please assign the issue to me

**Comment by Venkat230407** [comment]
Please assign this to me

**Comment by ashokdey** [comment]
Following FIFO, I have assigned it to @Mk996, if he fails in 3 hrs I will assign it to @Venkat230407

**Comment by ashokdey** [comment]
> Please assign the issue to me

You are good to go @Mk996

**Comment by TheSTL** [comment]
Closing this issue.
Merging PR - [# 52](https://github.com/knaxus/problem-solving-javascript/pull/52)
