### ISSUE TITLE
Add Reverse first k elements of queue problem and solution

### ISSUE THREAD

**Issue by SumeetHaryani** [knaxus/problem-solving-javascript#58]
Add Reverse first k elements of queue problem and solution

**Comment by iamshadmirza** [comment]
I would like to work on this.

**Comment by SumeetHaryani** [comment]
Sorry @iamshadmirza, this issue is already been referenced with PR #55.

**Comment by iamshadmirza** [comment]
No problem. Let me know if we can add more problems to the repo or any other way I can contribute.

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#81 ]
