### ISSUE TITLE
Queue data structure

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#60]
### Need following functions in queue:
File location - [Queue](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Queue/index.js)

1. empty() – Returns whether the queue is empty.
2. size() – Returns the size of the queue.
3. front() – Function returns a the first element of the queue.
4. back() – Function returns a  the last element of the queue.
5. push(g) – Function adds the element ‘g’ at the end of the queue.
6. pop() – Function deletes the first element of the queue.

Example:

Queue  q = [1,2,3,4,5,6];
q.empty()  `false`
q.size() `6`
q.front() `1`
q.back() `6`
q.push(10) `[1, 2, 3, 4, 5, 6, 10]`
q.pop() `[2, 3, 4, 5, 6, 10]`

**Comment by SumeetHaryani** [comment]
@TheSTL, can I work on this issue #60.

**Comment by ashokdey** [comment]
I will be taking care of this.

**Comment by makmandy** [comment]
Does this still need to be worked on, since @ashokdey 's PR has been merged

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#80 ]

**Comment by ashokdey** [comment]
@makmandy you can look into other issues. We got a bunch of issues around. Also, you can look into other repos of this organization.
