### ISSUE TITLE
postfix-expression-evaluation

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#61]
File location [postfix-expression-evaluation](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Stack/postfix-expression-evaluation/index.js)

If too few number arguments are passed then it should throw error or expression is not in order.
Few cases: 
- `12` Error
- `1` Error
- `+` Error
- `1+2` Error
- `+12` Error

**Comment by jasbindar-singh** [comment]
How do I run the project on my local machine?

**Comment by TheSTL** [comment]
Clone this repo and then run command npm install.

**Comment by jasbindar-singh** [comment]
That will just install the dependencies, then?

**Comment by TheSTL** [comment]
Then, node [file_path_to_run]

**Comment by vobango** [comment]
If nobody wants this, I can start working on it on Monday.

**Comment by TheSTL** [comment]
Hi @vobango , we are not getting your commit properly . Please setup you git properly.

**Comment by ashokdey** [comment]
> How do I run the project on my local machine?

Hello @jasbindar-singh, there is nothing to set up, it's a dead-simple project.

**Comment by jasbindar-singh** [comment]
How do I run and see outputs can you elaborate. @ashokdey

**Comment by TheSTL** [comment]
@vobango are you working on this issue?

**Comment by k88manish** [comment]
Can i take this up?

**Comment by TheSTL** [comment]
Yes you can work on this @k88manish

**Comment by k88manish** [comment]
@TheSTL Can you review my PR https://github.com/knaxus/problem-solving-javascript/pull/118

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is -[#129 ]
