### ISSUE TITLE
Add unit tests for BST Traversals

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#64]
Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by TheSTL** [comment]
I'am closing this issue.
Merged PR : [#70 ](https://github.com/knaxus/problem-solving-javascript/pull/70)
