### ISSUE TITLE
Add unit test for BST insertion

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#65]
Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by balajipachai** [comment]
Please refer #69

**Comment by TheSTL** [comment]
Closing this issue.
Merged PR - [#67  ] and [#69 ]
