### ISSUE TITLE
Add unit test for BST deletion

### ISSUE THREAD

**Issue by ashokdey** [knaxus/problem-solving-javascript#66]
Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by iamshadmirza** [comment]
I'll need a little help with this PR @ashokdey . I'm sure I followed the right coding convention for writing tests. Please review

**Comment by ashokdey** [comment]
@iamshadmirza can you refer the PR here? Which PR you are exactly taking about?

**Comment by iamshadmirza** [comment]
Both are reviewed and merged successfully. They were #67 for insert() test and #86 for delete() test for BST.

**Comment by TheSTL** [comment]
Closing this issue.
Merged PR - [#86 ]
