### ISSUE TITLE
Add Unit Test for - LRU Cache

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#71]
### 🤡 What is required?
The algorithm is here : [LRU-Cache](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Algorithms_/lru-cache)

- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by luhego** [comment]
I create a pull request for this issue:
https://github.com/knaxus/problem-solving-javascript/pull/77

**Comment by TheSTL** [comment]
I'm closing this issue because PR is merged. [#77 ]
