### ISSUE TITLE
Implement Jump search

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#74]
### 🕵️‍♂️ What is required?
You can learn about it from [here](https://www.geeksforgeeks.org/jump-search/)
- Create a new folder in [_Searching_](https://github.com/knaxus/problem-solving-javascript/tree/master/src/_Searching_) 
- Follow the ESLint rules strictly
- Follow the filename and folder structure strictly
- Since the Contribution Guide is not ready yet, go through the codebase pattern and add tests accordingly

Thank You!

**Comment by nik72619c** [comment]
working on this one

**Comment by gabrielbarker** [comment]
just made PR for this, sorry @nik72619c

**Comment by nik72619c** [comment]
oops, my bad !

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR - [#78 ]
