### ISSUE TITLE
addAt function in linked-list

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#82]
Linked-list addAt function not working properly.
File location [linked-list](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/LinkedList/index.js)

Please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by fluffynuts** [comment]
This appears to be working correctly in `master` (there's a passing test too). What's the issue?

**Comment by TheSTL** [comment]
@fluffynuts  
- Case 1:
linkedList.addAt(0, 1);
linkedList.addAt(0 ,2);
output : `{ data: 1, next: Node { data: 2, next: null } }`
- Case 2:
linkedList.addAt(0, 1);
linkedList.addAt(0 ,2);
linkedList.addAt(2 ,3);
output: `{ data: 1, next: Node { data: 3, next: null } }`

There can be more cases where it can fail

**Comment by ashu8912** [comment]
Hey Can I take this issue.

**Comment by ashokdey** [comment]
ok

**Comment by ashu8912** [comment]
#103
