### ISSUE TITLE
removeAt function in linked-list

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#83]
Linked-list removeAt function not working properly.
File location [linked-list](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/LinkedList/index.js)

Please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by adavijit** [comment]
Please assign this to me

**Comment by TheSTL** [comment]
hi @adavijit can you solve this issue?

**Comment by adavijit** [comment]
No! please assign it to others! I am getting the wrong result

**Comment by TheSTL** [comment]
@adavijit  Your try is not bad , i can see in PR- [#84 ].
There are 3 cases in removeAt:
- If index =0, then this.head = this.head.next
- Else If index = linkedList.length -1, then find previous node and set next value to null (previous.next = null)
- Else find previous (i-1) and current (i)  node, then previous.next = current.next;

If you think i'm wrong you can tell me.
Do you want to try it again?

**Comment by adavijit** [comment]
Yes! I am trying

**Comment by k88manish** [comment]
Hi @adavijit, Are you still working on this? If not I pick this up.
