### ISSUE TITLE
Add Unit Test for - Suffix Tree

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#87]
File location : [Suffix tree](https://github.com/knaxus/problem-solving-javascript/blob/master/src/_DataStructures_/Trees/SuffixTree/index.js)
Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by faergeek** [comment]
Hi! Can I take this one?

**Comment by TheSTL** [comment]
@faergeek  yes you can work on this.
