### ISSUE TITLE
Implement  Binary Tree to Binary Search Tree Conversion

### ISSUE THREAD

**Issue by TheSTL** [knaxus/problem-solving-javascript#90]
For more information- [Binary Tree to Binary Search Tree Conversion](https://www.geeksforgeeks.org/binary-tree-to-binary-search-tree-conversion/)

Hello folks, please go through the Contribution Guide here [https://github.com/knaxus/problem-solving-javascript#contribution-guide](https://github.com/knaxus/problem-solving-javascript#contribution-guide) before going forward with this issue. 

Thanks

**Comment by k88manish** [comment]
Let me try this

**Comment by k88manish** [comment]
Added https://github.com/knaxus/problem-solving-javascript/pull/95. Please review

**Comment by k88manish** [comment]
Raised new PR #127

**Comment by TheSTL** [comment]
I'm closing this issue.
Merged PR is [#127 ]

**Comment by k88manish** [comment]
Thanks @TheSTL  and @ashokdey.

**Comment by ashokdey** [comment]
Do star this repo and share on social media if you liked working on it.
